name: 'Compile & publish NuGet package'
description: 'One-step CI/DI as well as deployment for C# and NodeJS projects.'
author: 'ffMathy'
inputs:
  gitHubToken:
    description: 'API key for GitHub'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'